version: '3.8'

services:
  db:
    image: postgres:14
    container_name: supply_demand
    restart: always
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: supply_demand
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
